version: 2

models:
  - name: silver_cleaned_customers
    columns:
      - name: customer_id
        tests: [unique, not_null]

  - name: silver_cleaned_orders
    columns:
      - name: order_id
        tests: [unique, not_null]
      - name: customer_id
        tests: [not_null]

  - name: silver_cleaned_products
    columns:
      - name: product_id
        tests: [unique, not_null]
      - name: price
        tests:
          - dbt_utils.expression_is_true:
              expression: "{{price}} >= 0"

  - name: silver_cleaned_order_items
    columns:
      - name: order_id
        tests: 
          - not_null
      - name: product_id
        tests: 
          - not_null
      - name: quantity
        tests:
          - dbt_utils.expression_is_true:
              expression: "{{quantity}} > 0"