version: 2

sources:
  - name: demo_db
    database: demo_db
    schema: demo_schema
    tables:
      - name: customers
        tests:
          - unique:
              column_name: customer_id
          - not_null:
              column_name: customer_id
      - name: products
        tests:
          - unique:
              column_name: product_id
          - not_null:
              column_name: product_id
      - name: orders
        tests:
          - unique:
              column_name: order_id
          - not_null:
              column_name: order_id
      - name: order_items
        tests:
          - not_null:
              column_name: order_id
          - not_null:
              column_name: product_id
